SELECT D2.NAME FROM DEPARTMENTS D2
JOIN (
SELECT D.DEPARTMENTID AS DID , COUNT(E.EMPLOYEEID) AS COUNTEMPLOYEE 
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON E.DEPARTMENTID = D.DEPARTMENTID 
GROUP BY D.NAME
) COUNTDEPARTMENT ON COUNTDEPARTMENT.DID = D2.DEPARTMENTID
WHERE  COUNTDEPARTMENT.COUNTEMPLOYEE < 3